### ISSUE TITLE
fs.rename() can crash with cross-mount renames

### ISSUE THREAD

**Issue by depau** [reproducible-containers/buildkit-cache-dance#41]
This line: https://github.com/reproducible-containers/buildkit-cache-dance/blob/5b6db76d1da5c8b307d5d2e0706d266521b710de/src/extract-cache.ts#L46

It fails if you specify a cache location that is in a different mountpoint than the scratch directory. This can happen on AWS CodeBuild if you place the cache directory in the home directory, like this log below.

```
 Post job cleanup.

FROM busybox:1
COPY buildstamp buildstamp
RUN --mount=type=cache,target=/root/.npm     mkdir -p /var/dance-cache/     && cp -p -R /root/.npm/. /var/dance-cache/ || true

Error: EXDEV: cross-device link not permitted, rename 'scratch/dance-cache' -> '/root/.cache/docker-build-cache/root/.npm'
    at async Object.rename (node:internal/fs/promises:779:10)
    at async $8d40300f3635b768$var$extractCache (file:///codebuild/output/src2102109131/src/actions-runner/_work/_actions/reproducible-containers/buildkit-cache-dance/v3.1.0/dist/index.js:1374:5)
    at async $8d40300f3635b768$export$bd3cfa0c41fc7012 (file:///codebuild/output/src2102109131/src/actions-runner/_work/_actions/reproducible-containers/buildkit-cache-dance/v3.1.0/dist/index.js:1384:72)
    at async $bec5d2ddaaf4a876$var$main (file:///codebuild/output/src2102109131/src/actions-runner/_work/_actions/reproducible-containers/buildkit-cache-dance/v3.1.0/dist/index.js:1393:5)
    at async file:///codebuild/output/src2102109131/src/actions-runner/_work/_actions/reproducible-containers/buildkit-cache-dance/v3.1.0/dist/index.js:1401:5 {
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: 'scratch/dance-cache',
  dest: '/root/.cache/docker-build-cache/root/.npm'
}
Error: EXDEV: cross-device link not permitted, rename 'scratch/dance-cache' -> '/root/.cache/docker-build-cache/root/.npm'
    at async Object.rename (node:internal/fs/promises:779:10)
    at async $8d40300f3635b768$var$extractCache (file:///codebuild/output/src2102109131/src/actions-runner/_work/_actions/reproducible-containers/buildkit-cache-dance/v3.1.0/dist/index.js:1374:5)
    at async $8d40300f3635b768$export$bd3cfa0c41fc7012 (file:///codebuild/output/src2102109131/src/actions-runner/_work/_actions/reproducible-containers/buildkit-cache-dance/v3.1.0/dist/index.js:1384:72)
    at async $bec5d2ddaaf4a876$var$main (file:///codebuild/output/src2102109131/src/actions-runner/_work/_actions/reproducible-containers/buildkit-cache-dance/v3.1.0/dist/index.js:1393:5)
    at async file:///codebuild/output/src2102109131/src/actions-runner/_work/_actions/reproducible-containers/buildkit-cache-dance/v3.1.0/dist/index.js:1401:5
```

I fixed the issue in my code by simply moving the cache directory into the workspace.

I thought I'd let you know anyway, in case you want to wrap this in a try-catch and copy the directory on failure or just document this quirk.

Have a great day!

**Comment by MidnightRocket** [comment]
I also got this issue. It seems to me that a reasonable fallback would to just copy the files as suggested by @depau.
